# Generated by Django 4.2.7 on 2023-11-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_player_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='skill',
            new_name='endurance',
        ),
        migrations.AddField(
            model_name='player',
            name='gameIntelligence',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mindset',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='teamPlayer',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='technique',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
