# Generated by Django 4.2.7 on 2023-11-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_skill_player_endurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_level',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
