# Generated by Django 4.2.7 on 2023-11-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_player_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='endurance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gameIntelligence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mindset',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='teamPlayer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='technique',
            field=models.IntegerField(null=True),
        ),
    ]
